### ISSUE TITLE
Persist voice configurations after closing side panel 

### ISSUE THREAD

**Issue by davuses** [yacine-bens/MsEdge-TTS-Extension#1]
Greetings! Thank you for this extension. I've always been on the lookout for a way to utilize Edge built-in TTS functionality. And here we have it!

The only issue I have is that the voice configs will reset once the extension side panel is closed. So I wonder if there's a way to retain those settings until further changes are made?

**Comment by yacine-bens** [comment]
Hey there! I'm glad you found this extension useful.
Thank you for reporting this issue. It makes sense to persist voice configs. I'll look into it.

**Comment by yacine-bens** [comment]
The extension now saves voices configs and loads them when the side panel is open. The extension update in the Mozilla / Chrome store will go through a review process so it'll take some time. Are you installing it manually or from the store?

**Comment by yacine-bens** [comment]
This feature is added to Firefox version as well.

**Comment by davuses** [comment]
> The extension now saves voices configs and loads them when the side panel is open. The extension update in the Mozilla / Chrome store will go through a review process so it'll take some time. Are you installing it manually or from the store?

Thank you! I build the extension with the latest update and It works perfectly for me.

**Comment by yacine-bens** [comment]
I'm glad I could help. Thank you for your feedback.
